#
# This is the DASH configuration makefile for Xperia SP.
#

# ST-iNemo
SOMC_CFG_SENSORS_ACCELEROMETER_LSM303DLHC_LT := yes
SOMC_CFG_SENSORS_COMPASS_LSM303DLHC := yes
SOMC_CFG_SENSORS_GYRO_L3GD20 := yes

# Compass Sensor
SOMC_CFG_SENSORS_COMPASS_AK8963 := yes

# Proximity Sensor
SOMC_CFG_SENSORS_PROXIMITY_APDS9702 := yes

# configure light sensor
SOMC_CFG_SENSORS_LIGHT_AS3677 := yes
SOMC_CFG_SENSORS_LIGHT_AS3677_PATH := "/sys/devices/i2c-10/10-0040"
SOMC_CFG_SENSORS_LIGHT_AS3677_MAXRANGE := 1024
